### ISSUE TITLE
Error dynamicsConfig.json

### ISSUE THREAD

**Issue by blopezinz** [fsxmanu/dynamics-for-dev#21]
Hi, this is the error of the extension, i can't download webresource
can you help me? pls
![image](https://user-images.githubusercontent.com/29614146/141500059-559f0cb4-1a78-4439-88d2-5935ae8d8bc1.png)

**Comment by fsxmanu** [comment]
Hi

Thank you for downloading my extension 😄 

you first need to generate a dynamicsconfig.json file in that said path. You can just right click in an empty space of your workspace like this:
![image](https://user-images.githubusercontent.com/22397350/141501526-03bf11df-4354-45fa-961b-4a8bed8e374e.png)

You then need to configure it how it's shown in the readme on this repo. 

Please let me know if this helped you

**Comment by fsxmanu** [comment]
@blopezinz Actually I detectede an incompatibility with the Windows file system. I'm not on Windows so I haven't noticed that problem myself yet. Thank you for reporting this issue to me. I created a new branch and pull request #22 
If you switch to that path on the main site here you should be able to get the new vsix package and download it to install it manually. Can you report back if it's working? I will test it too and will release the update when I can ensure that all operations work on Windows too

**Comment by fsxmanu** [comment]
Not closed yet as author must be able to confirm.

@blopezinz I just released 0.7.2. I was able to up- and download webresources from dynamics. Also the solution export did work. Can you confirm it works with version 0.7.2?

**Comment by blopezinz** [comment]
Hi. Thanks for you answer. I download new version, but i can´t download the WebResource from Dynamics

**Comment by fsxmanu** [comment]
Hi 

Are you signed in via the Azure extension? Via the command palette you can enter "Azure: Sign In" and that should be enough. Otherwise you can try on the command line in vs code with "az login --allow-no-subscription" which did it for me. this is something I experienced when my user doesn't have an Azure Subscription. I will add it to the Known issues list

**Comment by blopezinz** [comment]
Hi @fsxmanu, i sign in with Azure extension but i can´t download webresource, don´t see a pop-up or other indicator.

**Comment by fsxmanu** [comment]
Hi @blopezinz 
Can you post the dynamicsconfig.json file here? With the Organization Url removed of course

**Comment by blopezinz** [comment]
Hi @fsxmanu
This is the file 
![image](https://user-images.githubusercontent.com/29614146/142861594-719834c7-eda3-4ba2-8e75-7b7e11be2340.png)

**Comment by fsxmanu** [comment]
interesting. I tried it just now when I right click and select "Download Web Resources from Dynamics" a list of webresources comes up. Do you have any webresources in the MyCustomizationSolution? Also are the webresources with the prefix "mcs_" already in the dynamics?

If there are many it could take a moment but it should give you a list at the top of the list with all available webresources.

**Comment by fsxmanu** [comment]
Hi @blopezinz I managed to get a Windows machine for testing.
1. Have you installed Azure CLI on your system? You may need to restart when you first installed it. https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
2. please run "az login" from the vs code terminal. For some reason the Azure: Login from the Command Pallette didn't work for me (may only be during debugging)

**Comment by fsxmanu** [comment]
Hi @blopezinz 
I have also released a new version 0.7.3 which should give you a message if something isn't working

**Comment by blopezinz** [comment]
Hi @fsxmanu 
The extension works, i can download the webresource in my folder thanks for you help.

**Comment by fsxmanu** [comment]
Good news. Sorry for the issue. I hope all will work now
