### ISSUE TITLE
Error on upload: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by YoYoFreakCJ** [fsxmanu/dynamics-for-dev#33]
# Issue

The following error occurs when trying to upload a web resource:

> There was an error getting the web resources. Reason: TypeError: Cannot read properties of undefined (reading 'length')

# Reproduction Steps

Create a folder structure like this

- myCompany_
  - ToolName
    - scripts
      - MyFiles.ts
- out
  - myCompany_
    - scripts
      - MyFiles.js
- dynamicsConfig.json

Contents of dynamicsConfig.json:

```json
{
    "NamingConvention": {
        "WebResourceFolder": [
            "/out/myCompany_/scripts"
        ],
        "Prefix": [
            "myCompany_"
        ]
    },
    "OrgInfo": {
        "CrmUrl": "https://myOrg.crm4.dynamics.com/",
        "ApiVersion": "9.1"
    },
    "UploadOptions": {
        "AddExistingToSolution": false,
        "TryToResolveFilePath": false
    },
    "Solutions": [
        "test"
    ]
}
```

Contents of the ts and js files are irrelevant.

Create a solution called "test" with the publisher prefix "myCompany_".

The existing solution has not been exported because it is empty.

The error occurs when right-clicking out/myCompany_/scripts/MyFiles.js and choosing "Upload WebResource to Dynamics".

**Comment by fsxmanu** [comment]
Hi

Thanks for reporting this issue. I'm currently away from home and don't have access to a dynamics instance. Do you get any other message or notification pop ups? 
I will look at the code now but I probably can't test it this week, sorry for that.

**Comment by fsxmanu** [comment]
So I investigated it and found a possible fix. Could you install this version I'm attaching here and try again? That would be nice of you. (I had to zip it, sorry)
[dynamics-for-dev-0.7.10.zip](https://github.com/fsxmanu/dynamics-for-dev/files/9298682/dynamics-for-dev-0.7.10.zip)

**Comment by YoYoFreakCJ** [comment]
The error does not occur anymore with this version. The web resource has successfully been created, published and added to the solution. Thank you for the quick fix!

**Comment by fsxmanu** [comment]
> The error does not occur anymore with this version. The web resource has successfully been created, published and added to the solution. Thank you for the quick fix!

Ghood to hear. I just updated the official version. Thanks for testing so quickly :)

**Comment by YoYoFreakCJ** [comment]
@fsxmanu sorry to abuse this issue for this (don't know how to talk to authors on GitHub) but would you be willing to allow branches from other users? I got a couple ideas to further improve the usability and productivity of this extension since there's a huge potential here I think and unless you want me to hassle you about it I'd just do it myself every now and then.

I'd prefer not using a fork.

**Comment by fsxmanu** [comment]
@YoYoFreakCJ no problem. Sure I'll be happy to do that. I just need to check how to do that because I want to be able to mark the pull requests before they get merged (just so not everyone can do it) I can give you permission for branches. will report back later

**Comment by fsxmanu** [comment]
> @fsxmanu sorry to abuse this issue for this (don't know how to talk to authors on GitHub) but would you be willing to allow branches from other users? I got a couple ideas to further improve the usability and productivity of this extension since there's a huge potential here I think and unless you want me to hassle you about it I'd just do it myself every now and then.
> 
> I'd prefer not using a fork.

@YoYoFreakCJ sent you an invite
